"""create initial tables

Revision ID: 61dab4850431
Revises: 
Create Date: 2026-08-17 14:15:40.120500
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '61dab4850431'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_anomaly_events_severity_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomaly_events')),
    sa.UniqueConstraint('symbol', 'trading_date', 'event_type', name='anomaly_event_identity')
    )
    op.create_index('ix_anomaly_events_symbol_trading_date', 'anomaly_events', ['symbol', 'trading_date'], unique=False)
    op.create_table('daily_bars',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('adjustment', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("adjustment IN ('raw', 'split_adjusted', 'total_return')", name=op.f('ck_daily_bars_adjustment_valid')),
    sa.CheckConstraint('high >= open AND high >= close AND high >= low', name=op.f('ck_daily_bars_high_price_range')),
    sa.CheckConstraint('high>0', name=op.f('ck_daily_bars_high_positive')),
    sa.CheckConstraint('low <= open AND low <= close AND low <= high', name=op.f('ck_daily_bars_low_price_range')),
    sa.CheckConstraint('low>0', name=op.f('ck_daily_bars_low_positive')),
    sa.CheckConstraint('open > 0', name=op.f('ck_daily_bars_open_positive')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_daily_bars_volume_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_bars')),
    sa.UniqueConstraint('symbol', 'trading_date', 'source', 'adjustment', name='daily_bar_identity')
    )
    op.create_index('ix_daily_bars_symbol_trading_date', 'daily_bars', ['symbol', 'trading_date'], unique=False)
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('symbol', sa.String(length=15), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('latest_quarter', sa.Date(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('price_to_book_ratio', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_snapshots')),
    sa.UniqueConstraint('symbol', 'snapshot_date', 'source', name='fundamental_snapshot_identity')
    )
    op.create_index('ix_fundamental_snapshots_symbol_snapshot_date', 'fundamental_snapshots', ['symbol', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fundamental_snapshots_symbol_snapshot_date', table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    op.drop_index('ix_daily_bars_symbol_trading_date', table_name='daily_bars')
    op.drop_table('daily_bars')
    op.drop_index('ix_anomaly_events_symbol_trading_date', table_name='anomaly_events')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###